import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import ConvexClientProvider from "@/components/ConvexClientProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en" className="dark h-full">
        <body className={`${inter.className} antialiased h-full bg-black`}>
          <ConvexClientProvider>
            <div
              className="
                w-full max-w-[420px] min-h-dvh 
                h-full
                bg-background
                mx-auto
                overflow-hidden
                /* iOS safe areas */
                pt-[env(safe-area-inset-top)]
                pb-[env(safe-area-inset-bottom)]
                pl-[env(safe-area-inset-left)]
                pr-[env(safe-area-inset-right)]
              "
            >
              {children}
            </div>
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
